### ISSUE TITLE
New device with hypens in product class

### ISSUE THREAD

**Issue by 5700** [zaidka/genieacs-gui#21]
Hi,

I have just pointed a new device the the CWMP server. It happens to have *hyphens* in the product class (I-20E-R), which I suspect is causing issues in various places.  Hyphen seems to be used to create a unique id for the device.

I have pulled the latest genieace-gui code from GIT, and it is the same.

When I go to show the device with the following URL I get this error:
```
URL:  http://127.0.0.1:3000/devices/086C7-I%252D20E%252DR-787634744

NoMethodError in Devices#show

Showing /usr/local/src/genieacs-new-gui/app/views/devices/_object_table.html.erb where line #26 raised:

undefined method `[]' for nil:NilClass

Extracted source (around line #26):

23
24
25
26
27
28
29
          

	

<td class="action">
<%= param_value("#{params['_object']}.#{k}.#{v2}", @device) rescue '' %>
<% v3 = get_param(v2, v) %>
<% if v3['_writable'] %>
<% options = Rails.configuration.parameters_edit["#{params['_object']}.#{k}.#{v2}".gsub(/\.\d+\./, '..')] %>
<a href="#" onclick='editParam("<%= "#{params['_object']}.#{k}.#{v2}" %>", "<%= v3['_type'] %>", "<%= v3['_value'] %>", <%= options.to_json.html_safe %>);return false;'>Edit</a>
<% end %>

Trace of template inclusion: app/views/devices/show.html.erb

Rails.root: /usr/local/src/genieacs-new-gui
Application Trace | Framework Trace | Full Trace

app/views/devices/_object_table.html.erb:26:in `block (2 levels) in _app_views_devices__object_table_html_erb__1935730364283490627_26293860'
app/views/devices/_object_table.html.erb:14:in `each'
app/views/devices/_object_table.html.erb:14:in `block in _app_views_devices__object_table_html_erb__1935730364283490627_26293860'
app/views/devices/_object_table.html.erb:11:in `each'
app/views/devices/_object_table.html.erb:11:in `_app_views_devices__object_table_html_erb__1935730364283490627_26293860'
app/views/devices/show.html.erb:61:in `block in _app_views_devices_show_html_erb__2676220600241539780_27607860'
app/views/devices/show.html.erb:48:in `each'
app/views/devices/show.html.erb:48:in `_app_views_devices_show_html_erb__2676220600241539780_27607860'
app/controllers/devices_controller.rb:107:in `block in show'
app/controllers/application_controller.rb:40:in `can?'
app/controllers/devices_controller.rb:101:in `show'

Request

Parameters:

{"id"=>"086C7-I%2D20E%2DR-787634744"}

Toggle session dump
Toggle env dump
Response

Headers:

None
```

The genieacs-cwmp.log look as below:
```
4 May 16:44:33 - 086C7-I%2D20E%2DR-787634744: Inform (0 BOOTSTRAP); retry count 0
2015-05-04T06:44:33.153Z - Error: EACCES, open './debug/086C7-I%2D20E%2DR-787634744.dump'
4 May 16:44:45 - 086C7-I%2D20E%2DR-787634744: Inform (0 BOOTSTRAP); retry count 1
2015-05-04T06:44:45.103Z - Error: EACCES, open './debug/086C7-I%2D20E%2DR-787634744.dump'
4 May 16:45:07 - 086C7-I%2D20E%2DR-787634744: Inform (0 BOOTSTRAP); retry count 2
2015-05-04T06:45:07.100Z - Error: EACCES, open './debug/086C7-I%2D20E%2DR-787634744.dump'
4 May 16:45:49 - 086C7-I%2D20E%2DR-787634744: Inform (0 BOOTSTRAP); retry count 3
2015-05-04T06:45:49.103Z - Error: EACCES, open './debug/086C7-I%2D20E%2DR-787634744.dump'
4 May 16:47:11 - 086C7-I%2D20E%2DR-787634744: Inform (0 BOOTSTRAP); retry count 4
4 May 16:47:11 - 086C7-I%2D20E%2DR-787634744: New device registered
4 May 16:47:14 - 086C7-I%2D20E%2DR-787634744: Started task refreshObject(554715ef1bddc3ae590fd314)
4 May 16:47:32 - 086C7-I%2D20E%2DR-787634744: Completed task refreshObject(554715ef1bddc3ae590fd314)
4 May 16:47:32 - 086C7-I%2D20E%2DR-787634744: Presets discrepancy found
4 May 16:47:32 - 086C7-I%2D20E%2DR-787634744: Updating tags +(Registered) -()
4 May 16:57:34 - 086C7-I%2D20E%2DR-787634744: Inform (2 PERIODIC); retry count 0
4 May 17:07:39 - 086C7-I%2D20E%2DR-787634744: Inform (2 PERIODIC); retry count 0
4 May 17:17:44 - 086C7-I%2D20E%2DR-787634744: Inform (2 PERIODIC); retry count 0
4 May 17:27:49 - 086C7-I%2D20E%2DR-787634744: Inform (2 PERIODIC); retry count 0
4 May 17:37:54 - 086C7-I%2D20E%2DR-787634744: Inform (2 PERIODIC); retry count 0
4 May 17:47:59 - 086C7-I%2D20E%2DR-787634744: Inform (2 PERIODIC); retry count 0
4 May 17:58:04 - 086C7-I%2D20E%2DR-787634744: Inform (2 PERIODIC); retry count 0
4 May 18:08:09 - 086C7-I%2D20E%2DR-787634744: Inform (2 PERIODIC); retry count 0
4 May 18:18:13 - 086C7-I%2D20E%2DR-787634744: Inform (2 PERIODIC); retry count 0
4 May 18:28:18 - 086C7-I%2D20E%2DR-787634744: Inform (2 PERIODIC); retry count 0
```

When I try to reference it via the NBI..
```
# curl -i 'http://localhost:7557/devices/086C7-I%25252D20E%25252DR-787634744/tasks?connection_request' -X POST --data '{"name":"refreshObject", "objectName":""}'
HTTP/1.1 500 Internal Server Error
Connection: close
Date: Mon, 04 May 2015 08:55:37 GMT
Transfer-Encoding: chunked
```

I get the following in the genieacs-nbi.log
```
2015-05-04T08:55:37.777Z - TypeError: Cannot read property 'Device' of null
    at /usr/local/src/genieacs-new/lib/api-functions.js:116:15
    at /usr/local/src/genieacs-new/node_modules/mongodb/lib/mongodb/collection/query.js:159:5
    at /usr/local/src/genieacs-new/node_modules/mongodb/lib/mongodb/cursor.js:758:35
    at Cursor.close (/usr/local/src/genieacs-new/node_modules/mongodb/lib/mongodb/cursor.js:989:5)
    at Cursor.nextObject (/usr/local/src/genieacs-new/node_modules/mongodb/lib/mongodb/cursor.js:758:17)
    at commandHandler (/usr/local/src/genieacs-new/node_modules/mongodb/lib/mongodb/cursor.js:727:14)
    at b (domain.js:183:18)
    at /usr/local/src/genieacs-new/node_modules/mongodb/lib/mongodb/db.js:1890:9
    at b (domain.js:183:18)
    at Server.Base._callHandler (/usr/local/src/genieacs-new/node_modules/mongodb/lib/mongodb/connection/base.js:448:41)
```

Am I on the right track with the hyphens in the product class?

Any ideas on where to go next?

Thanks in advance :)

Stuart

**Comment by zaidka** [comment]
Hyphens shouldn't be a problem if URL escaping is done correctly. It can be confusing sometimes though. Try the following:

    curl -i 'http://localhost:7557/devices/086C7-I%252D20E%252DR-787634744/tasks?connection_request' -X POST --data '{"name":"refreshObject", "objectName":""}'

**Comment by 5700** [comment]
Thanks.   I have paid closer attention to the escaping.  I still have issues, so perhaps it is with the data whe being retrieved.

I can display of all the data for the device via the NBI, and it is long, so have omitted here for now. 
```
curl  'http://localhost:7557/devices/?query=%7B%22_id%22%3A%22086C7-I%252D20E%252DR-787634744%22%7D'
```



When performing a refresh: 
```
curl -i 'http://localhost:7557/devices/086C7-I%252D20E%252DR-787634744/tasks?connection_request' -X POST --data '{"name":"refreshObject", "objectName":""}'

```
it produces an error in nbi.log:
```
7 May 17:56:12 - Worker 31615 listening to 0.0.0.0:7557
2015-05-07T07:56:21.670Z - TypeError: Cannot read property '0' of undefined
    at /usr/local/src/genieacs-new/lib/api-functions.js:124:72
    at ClientRequest.<anonymous> (/usr/local/src/genieacs-new/lib/api-functions.js:90:7)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1693:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
    at Socket.socketOnData [as ondata] (http.js:1588:20)
    at TCP.onread (net.js:528:27)
```

Using the web interface, the device is displayed fine on http://127.0.0.1:3000/devices
but when clicking "show" on that device will give the error page below:
```
URL: http://127.0.0.1:3000/devices/086C7-I%252D20E%252DR-787634744

NoMethodError in Devices#show 

Showing /usr/local/src/genieacs-new-gui/app/views/devices/  where line #26 raised:

undefined method `[]' for nil:NilClass

Extracted source (around line #26):

<td class="action">
<%= param_value("#{params['_object']}.#{k}.#{v2}", @device) rescue '' %>
<% v3 = get_param(v2, v) %>
<% if v3['_writable'] %>                                                                                           #### THIS LINE IS HIGHLIGHTED
<% options = Rails.configuration.parameters_edit["#{params['_object']}.#{k}.#{v2}".gsub(/\.\d+\./, '..')] %>
<a href="#" onclick='editParam("<%= "#{params['_object']}.#{k}.#{v2}" %>", "<%= v3['_type'] %>", "<%= v3['_value'] %>", <%= options.to_json.html_safe %>);return false;'>Edit</a>
<% end %>

Trace of template inclusion: app/views/devices/show.html.erb

Rails.root: /usr/local/src/genieacs-new-gui
Application Trace | Framework Trace | Full Trace

app/views/devices/_object_table.html.erb:26:in `block (2 levels) in _app_views_devices__object_table_html_erb__1935730364283490627_70316247321620'
app/views/devices/_object_table.html.erb:14:in `each'
app/views/devices/_object_table.html.erb:14:in `block in _app_views_devices__object_table_html_erb__1935730364283490627_70316247321620'
app/views/devices/_object_table.html.erb:11:in `each'
app/views/devices/_object_table.html.erb:11:in `_app_views_devices__object_table_html_erb__1935730364283490627_70316247321620'
app/views/devices/show.html.erb:61:in `block in _app_views_devices_show_html_erb__2676220600241539780_27607860'
app/views/devices/show.html.erb:48:in `each'
app/views/devices/show.html.erb:48:in `_app_views_devices_show_html_erb__2676220600241539780_27607860'
app/controllers/devices_controller.rb:107:in `block in show'
app/controllers/application_controller.rb:40:in `can?'
app/controllers/devices_controller.rb:101:in `show'

Request Parameters:

{"id"=>"086C7-I%2D20E%2DR-787634744"}
```

Is there something missing from my data set, it appears to have the entire CWMP tree, as well as objects "_value", "_timestamp", "_type", "xsd:string" and "_writable"

Is there something I can add to the _object_table.html.erb that might print out what was the object with the error?  I have not used Ruby before.

Thanks, Stuart

**Comment by 5700** [comment]
Hi,

I have jumped into Ruby and worked out my problem (related to config).
I modified the erroring line (shown previously) to spit out a HTML comment, and be able to skip getting an error if the value was nil (null).
```
<% if v3['_writable'] %>
```
to 
```
<% if v3.nil? %>
         <!-- found nill or missing data -->
<% end %>
<% if ! v3.nil? and v3['_writable'] %>
```

With this the page generated, and I found the HTML comment that was inserted, and found that it was directly related some settings in config/summary_parameters.yml that I had for another device.  This device did not have the information available.  I really would love to support multiple devices, I guess I could do this by having multiple GUIs.

Thanks for you help anyway, and thanks for this project.

:) Stuart

**Comment by zaidka** [comment]
Glad you had this figured out. But you shouldn't need to have separate GUI's for different models. This needs to be fixed. Will leave this ticket open until it's fixed. Thanks.

**Comment by sthasanto** [comment]
Have you fixed the issue yet? I am having same issues when the product class has hypens. Its adding %2D in genieacs and mongo. So remote configuration of these device is impossible.

**Comment by ppkamp** [comment]
I have the same issue.
It's like the hypen is urlencoded inside _id field.
Maybe doing a urldecode before saving the _id should be enough...

**Comment by sthasanto** [comment]
> Is this problem solved in v1.2?

Not solved in v1.2 also.

**Comment by zaidka** [comment]
The percent encoding of some characters in the device ID is intentional.

**Comment by sthasanto** [comment]
> The percent encoding of some characters in the device ID is intentional.

Thank you for your quick response. Is there any impact without percent encoding in _id? If not, is there any way to sort out this issue? Because I have used Genieacs in our production network and because of this I am not able to work out with the device which has hyphens in product class. 
Your help in this matter is highly appreciated.

**Comment by zaidka** [comment]
I don't get what the issue is.

**Comment by sthasanto** [comment]
> I don't get what the issue is.

Dear Sir,

Device Id in 'Genieacs Server' and 'MongoDB' shows like  the following:
_id: 00259E-HG8546M%2DRMS-48575443373CFD90

But in 'API', device id shows as {_id : 00259E-HG8546M-RMS-48575443373CFD90}

So,  it treats both _ids as different and I'm not able to read/write parameters of this device with API.
Is there any possiblity to replace %2D with hyphen without creating any damage in the existing infrastructure?

Thank You.

**Comment by zaidka** [comment]
I don't see that being the case. Just double checked and I'm getting the correct ID from the API (hyphen properly escaped).

**Comment by sthasanto** [comment]
> I have the same issue.
> The problem is that you always have to urlencode the unit _id in API calls.
> From console curl, It is not possible to call some functions based on the unit _id field (although you urlencode it), but from php_curl I have no problem at all.
> 
> So if the _id is 086C7-I%2D20E%2DR-787634744
> urlencoded is 086C7-I%252D20E%252DR-787634744
> 
> It seems that GenieACS replace the hyphen with %2D when, in my opinion, there is no need to...

This helped me to solve the issue. Just like his comment we have to urlencode every time _id.

**Comment by zaidka** [comment]
Yes, you should always pass any dynamic values though an escape function when you're generating a URL. This is an HTTP thing and not specific to Genie.
