### ISSUE TITLE
Errno::ECONNREFUSED in HomeController#index

### ISSUE THREAD

**Issue by mrmatrixdiaz** [zaidka/genieacs-gui#27]
i try connect to http://<ip_address>:3000 and give this error.
can helpe me solve the error?

Errno::ECONNREFUSED in HomeController#index
Connection refused - connect(2) for "localhost" port 7557

Extracted source (around line #14):
12
13
14
15
16
17
          
          for graph_name, graph in group_graphs
            for slice in graph
              res = http.head("/devices/?query=#{CGI::escape ActiveSupport::JSON.encode(slice['query'])}")
              slice['data'] = res['Total'].to_i
              slice['href'] = url_for(controller: 'devices', action: 'index', params: {query: ActiveSupport::JSON.encode(slice['query'])}, only_path: true)
              slice.delete('query')

Rails.root: /opt/genieacs/genieacs-gui

Application Trace | Framework Trace | Full Trace
app/controllers/home_controller.rb:14:in `block (5 levels) in index'
app/controllers/home_controller.rb:13:in `each'
app/controllers/home_controller.rb:13:in `block (4 levels) in index'
app/controllers/home_controller.rb:12:in `each'
app/controllers/home_controller.rb:12:in `block (3 levels) in index'
app/controllers/home_controller.rb:11:in `each'
app/controllers/home_controller.rb:11:in `block (2 levels) in index'
app/controllers/home_controller.rb:6:in `block in index'
app/controllers/application_controller.rb:40:in `can?'
app/controllers/home_controller.rb:5:in `index'
Request

Parameters:

None
Toggle session dump
Toggle env dump
Response

Headers:

None

**Comment by akcoder** [comment]
The GUI can't connect to the NBI. Verify the NBI is running. If you have
the NBI running on a different server, or have it bound to an IP, then you
will need to update the GUI config with that information.

-dan

**Comment by sunilari** [comment]
Hi,

I am new on the GenieACS. I have installed all the required packages. But getting the error "Connection refused - connect(2) for "localhost" port 7557" while running the "http://localhost:3000/" in the browser.

1. on the Browser::
-------------------------------------------------------------------------------------------------

Errno::ECONNREFUSED in HomeController#index
Connection refused - connect(2) for "localhost" port 7557
Extracted source (around line #17):

15
16
17
18
19
20
              

	

              threads << Thread.new(slice) do |slice|
                http = create_api_conn()
                res = http.head("/devices/?query=#{CGI::escape ActiveSupport::JSON.encode(slice['query'])}")
                slice['data'] = res['Total'].to_i
                slice['href'] = url_for(controller: 'devices', action: 'index', params: {query: ActiveSupport::JSON.encode(slice['query'])}, only_path: true)
                slice.delete('query')

Rails.root: /opt/genieacs-gui
Application Trace | Framework Trace | Full Trace

app/controllers/home_controller.rb:17:in `block (6 levels) in index'
--------------------------------------------------------------------------------------------------------

2. On Terminal::
--------------------------------------------------------------------------------------------------------
root@user-PowerEdge-R810:/opt/genieacs-gui# rails server
=> Booting Puma
=> Rails 5.0.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.5.2 (ruby 2.2.6-p396), codename: Amateur Raccoon Rocketry
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop

Started GET "/" for 127.0.0.1 at 2016-12-07 20:10:07 +0530
  ActiveRecord::SchemaMigration Load (0.3ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by HomeController#index as HTML
Completed 500 Internal Server Error in 30ms (ActiveRecord: 0.0ms)


  
Errno::ECONNREFUSED (Connection refused - connect(2) for "localhost" port 7557):
  
app/controllers/home_controller.rb:17:in `block (6 levels) in index'
  Rendering /usr/local/lib/ruby/gems/2.2.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout
  Rendering /usr/local/lib/ruby/gems/2.2.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
  Rendered /usr/local/lib/ruby/gems/2.2.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (3.2ms)
  Rendering /usr/local/lib/ruby/gems/2.2.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /usr/local/lib/ruby/gems/2.2.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.6ms)
  Rendering /usr/local/lib/ruby/gems/2.2.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered /usr/local/lib/ruby/gems/2.2.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.6ms)
  Rendered /usr/local/lib/ruby/gems/2.2.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (51.2ms)

--------------------------------------------------------------------------------------------------------

3. no output for:
root@user-PowerEdge-R810:/opt/genieacs# ./bin/genieacs-nbi
root@user-PowerEdge-R810:/opt/genieacs#

4. 
root@user-PowerEdge-R810:/opt/genieacs# netstat | grep 7557
root@user-PowerEdge-R810:/opt/genieacs#

5. config.json file:

{
  "MONGODB_CONNECTION_URL" : "mongodb://127.0.0.1/genieacs",
  "REDIS_PORT" : "6379",
  "REDIS_HOST" : "127.0.0.1",
  "CWMP_INTERFACE" : "0.0.0.0",
  "CWMP_PORT" : 7547,
  "CWMP_SSL" : false,
  "NBI_INTERFACE" : "0.0.0.0",
  "NBI_PORT" : 7557,
  "FS_INTERFACE" : "0.0.0.0",
  "FS_PORT" : 7567,
  "FS_IP" : "192.168.0.1",
  "LOG_INFORMS" : true,
  "DEBUG" : false
}


6. 
I am using Ubuntu 14.04, no VM, Firewall was on/off, proxy was on/off

If genieacs-nbi is not working, how to start it? how to verify that if same is working fine? How to check port 7557 is accessible? How the port 7557 would be accessible, if not?  

Thanks in advance!!
- Sunil
