### ISSUE TITLE
genieacs-cwmp getting error 

### ISSUE THREAD

**Issue by hkachhia** [zaidka/genieacs-gui#54]
After configuration genieacs and trying to access using **genieacs-cwmp** getting below error

/usr/local/lib/node_modules/genieacs/lib/cluster/lib/worker.js:14
  , binding = process.binding('net')
                      ^
Error: No such module
    at Object.<anonymous> (/usr/local/lib/node_modules/genieacs/lib/cluster/lib/worker.js:14:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/genieacs/lib/cluster/lib/master.js:12:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

**Comment by DrumSergio** [comment]
Hi @hkachhia !

Better to post this in the mailing list: http://lists.genieacs.com/mailman/listinfo there you can receive more help if you explain better what you've installed and how.

Thank you!
