### ISSUE TITLE
ArgumentError (key must be 32 bytes)

### ISSUE THREAD

**Issue by agabellini** [zaidka/genieacs-gui#76]
Hello,

just installed the GUI with Ruby 2.4.1. At the first connection I get this error:

Processing by HomeController#index as HTML
  Rendering home/index.html.erb within layouts/application
  Rendered home/index.html.erb within layouts/application (2.1ms)
  Rendered layouts/_menu.html.erb (3.2ms)
Completed 200 OK in 104ms (Views: 86.4ms | ActiveRecord: 0.0ms)

ArgumentError (key must be 32 bytes):
  
activesupport (5.0.0) lib/active_support/message_encryptor.rb:72:in `key='
activesupport (5.0.0) lib/active_support/message_encryptor.rb:72:in `_encrypt'
activesupport (5.0.0) lib/active_support/message_encryptor.rb:58:in `encrypt_and_sign'
actionpack (5.0.0) lib/action_dispatch/middleware/cookies.rb:592:in `commit'
actionpack (5.0.0) lib/action_dispatch/middleware/cookies.rb:465:in `[]='
actionpack (5.0.0) lib/action_dispatch/middleware/session/cookie_store.rb:117:in `set_cookie'
rack (2.0.1) lib/rack/session/abstract/id.rb:353:in `commit_session'
rack (2.0.1) lib/rack/session/abstract/id.rb:224:in `context'
rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.0.0) lib/active_record/migration.rb:552:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.0) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.0) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.0) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.0) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
web-console (3.3.1) lib/web_console/middleware.rb:131:in `call_app'
web-console (3.3.1) lib/web_console/middleware.rb:20:in `block in call'
web-console (3.3.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.3.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.0) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.0) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.0) lib/active_support/tagged_logging.rb:70:in `block in tagged'
activesupport (5.0.0) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.0) lib/active_support/tagged_logging.rb:70:in `tagged'
railties (5.0.0) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.1.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
railties (5.0.0) lib/rails/engine.rb:522:in `call'
puma (3.5.2) lib/puma/configuration.rb:225:in `call'
puma (3.5.2) lib/puma/server.rb:569:in `handle_request'
puma (3.5.2) lib/puma/server.rb:406:in `process_client'
puma (3.5.2) lib/puma/server.rb:271:in `block in run'
puma (3.5.2) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
  Rendering /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout
  Rendering /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
  Rendered /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (6.6ms)
  Rendering /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (3.3ms)
  Rendering /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.5ms)
  Rendered /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (45.5ms)

This problem seems to be fixed in rails 5.0.2: https://github.com/rails/rails/issues/25448

Updating rails to 5.0.3 with "bundle update rails --minor" solve the problem, but changes many other gems

To solve this problem and the json version problem of the previous issue I installed ruby 2.3.4 :-)

Andrea

**Comment by mltsy** [comment]
My coworker is having the same problem on Ruby 2.3.3, Rails 5.0.0.1.  It works fine for my however, and the only oddity/difference I can see between our environments is that his OpenSSL version is 0.9.8 (old), and he's had trouble upgrading so I can't test that as a fix ATM. Just wanted to add that profile to the report, for posterity.

**Comment by agabellini** [comment]
Hello,

I use OpenSSL 1.0.1. Which versions of software do you use in the working environment?

Andrea

**Comment by mltsy** [comment]
The only difference I know of in my working environment is OpenSSL, which is 1.0.2g on mine.  Ruby and Rails are the same.  But I'm also on Ubuntu and the failing environment is OSX, so there is obviously a lot that could be different there, which I forgot to mention! :smile:

**Comment by mltsy** [comment]
FYI, I did finally get this in my Ubuntu staging environment - unfortunately I'm not sure how or why it suddenly started showing up. I was able to resolve it by updating Rails to 5.0.5 (as you mentioned).
